<template>
    <div>
        <HeadNavbar/>
       <BodyDon-lekside/> 
       <BodyAbout/>
       <BodySkill/>
       <BodyExperience/>
       <BodyWork/>
       <BodyGetInTouch/>
    </div>
</template>